### ISSUE TITLE
Commands not working.

### ISSUE THREAD

**Issue by zArby23** [zArby23/discord-bot#1]
While trying to use a command on the server, the bot doesn't responds and shows this message:

node:events:491
      throw er; // Unhandled 'error' event
      ^

TypeError: _**Cannot read properties of undefined (reading 'get')**_
    at Client.<anonymous> (**C:\Users\User\Desktop\-\discord-bot\index.js:32:48**)   
    at Client.emit (node:events:513:28)
    at InteractionCreateAction.handle (**C:\Users\User\Desktop\-\discord-bot\node_modules\discord.js\src\client\actions\InteractionCreate.js:81:12**)
    at module.exports [as INTERACTION_CREATE] (**C:\Users\User\Desktop\-\discord-bot\node_modules\discord.js\src\client\websocket\handlers\INTERACTION_CREATE.js:4:36**)
    at WebSocketManager.handlePacket (**C:\Users\User\Desktop\-\discord-bot\node_modules\discord.js\src\client\websocket\WebSocketManager.js:352:31**)
    at WebSocketShard.onPacket (**C:\Users\User\Desktop\-\discord-bot\node_modules\discord.js\src\client\websocket\WebSocketShard.js:480:22**)
    at WebSocketShard.onMessage (**C:\Users\User\Desktop\-\discord-bot\node_modules\discord.js\src\client\websocket\WebSocketShard.js:320:10**)
    at callListener (**C:\Users\User\Desktop\-\discord-bot\node_modules\ws\lib\event-target.js:290:14**)
    at WebSocket.onMessage (**C:\Users\User\Desktop\-\discord-bot\node_modules\ws\lib\event-target.js:209:9**)
    at WebSocket.emit (**node:events:513:28**)
Emitted 'error' event on Client instance at:
    at emitUnhandledRejectionOrErr **(node:events:394:10**)
    at process.processTicksAndRejections (**node:internal/process/task_queues:84:21**)

**Comment by zArby23** [comment]
Currently working on fixing it.

**Comment by zArby23** [comment]
> Currently working on fixing it.

Already fixed it. It was a spelling error, wrote "comand" instead of "command".
